/* Automatically generated by './build/bin/build-entry.js' */

import Table from '../packages/table/index.js';
import TableColumn from '../packages/table-column/index.js';
const components = [
  Table,
  TableColumn
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0-beta.0',
  install,
  Table,
  TableColumn
};
